### ISSUE TITLE
Implement all Cat 2 patches

### ISSUE THREAD

**Issue by shepdelacreme** [ansible-lockdown/RHEL7-STIG#44]
Currently there are ~~roughly 130~~ **19** Cat 2 STIG items that are not implemented in this role. Need to finish these before a 1.0 release. 

**High Priority CAT2 Items (always flagged by a benchmark):**
- [ ]  RHEL-07-040180  -  The operating system must implement cryptography to protect the integrity of Lightweight Directory Access Protocol (LDAP) authentication communications. (**breaks SSSD w/ Active Directory, should RAISE w/ DISA; AD connections are encrypted/authenticated w/ KRB5**)
- [ ]  RHEL-07-040190  -  The operating system must implement cryptography to protect the integrity of Lightweight Directory Access Protocol (LDAP) communications. (**default setting "hard" is compliant; DISA does not accept unconfigured value**)

**Priority CAT2 Items (not checked by any benchmark, non-complex):**
- [ ]  RHEL-07-020020  -  The operating system must prevent non-privileged users from executing privileged functions to include disabling, circumventing, or altering implemented security safeguards/countermeasures. (DISRUPTIVE!)
- [ ]  RHEL-07-020680  -  All files and directories contained in local interactive user home directories must have mode 0750 or less permissive. (WIP #282)
- [ ]  RHEL-07-020710  -  All local initialization files must have mode 0740 or less permissive.
- [ ]  RHEL-07-040200  -  The operating system must implement cryptography to protect the integrity of Lightweight Directory Access Protocol (LDAP) communications. (**consider configuring in /etc/openldap/ldap.conf instead of (or in addition to) sssd.conf**)
- [ ]  RHEL-07-040510  -  The operating system must protect against or limit the effects of Denial of Service (DoS) attacks by validating the operating system is implementing rate-limiting measures on impacted network interfaces.

**CAT2 Items (not checked by any benchmark, COMPLEX):**
- [ ]  RHEL-07-020720  -  All local initialization files must have mode 0740 or less permissive.
- [ ]  RHEL-07-020730  -  Local initialization files must not execute world-writable programs.
- [ ]  RHEL-07-021700  -  The system must not allow removable media to be used as the boot loader unless approved.

Remaining CAT 2 items:
- [ ]  RHEL-07-010500  -  The operating system must uniquely identify and must authenticate organizational users (or processes acting on behalf of organizational users) using multifactor authentication.
- [ ]  RHEL-07-021010  -  File systems that are used with removable media must be mounted to prevent files with the setuid and setgid bit set from being executed.
- [ ]  RHEL-07-021040  -  The umask must be set to 077 for all local interactive user accounts. (COMPLEX)
- [ ]  RHEL-07-040100  -  The host must be configured to prohibit or restrict the use of functions, ports, protocols, and/or services, as defined in the Ports, Protocols, and Services Management Component Local Service Assessment (PPSM CLSA) and vulnerability assessments.
- [ ]  RHEL-07-040750  -  The Network File System (NFS) must be configured to use RPCSEC_GSS.
- [ ]  RHEL-07-040810  -  The system's access control program must be configured to grant or deny system access to specific hosts and services.
- [x]  RHEL-07-010030  -  **GUI** The operating system must display the Standard Mandatory DoD Notice and Consent Banner before granting local or remote access to the system via a graphical user logon.
- [x]  RHEL-07-010040  - **GUI** The operating system must display the approved Standard Mandatory DoD Notice and Consent Banner before granting local or remote access to the system via a graphical user logon.
- [x]  RHEL-07-010060  -  **GUI** The operating system must enable a user session lock until that user re-establishes access using established identification and authentication procedures.
- [x]  RHEL-07-010061  -  **GUI** The operating system must uniquely identify and must authenticate users using multifactor authentication via a graphical user logon.
- [x]  RHEL-07-010070  -  **GUI** The operating system must initiate a screensaver after a 15-minute period of inactivity for graphical user interfaces.
- [x]  RHEL-07-010081  -  **GUI** The operating system must set the lock delay setting for all connection types.
- [x]  RHEL-07-010082  -  **GUI** The operating system must set the session idle delay setting for all connection types.
- [x]  RHEL-07-010100  -  **GUI** The operating system must initiate a session lock for the screensaver after a period of inactivity for graphical user interfaces.
- [x]  RHEL-07-010110  -  **GUI** The operating system must initiate a session lock for graphical user interfaces when the screensaver is activated.
- [x]  RHEL-07-020270  -  The system must not have unnecessary accounts.
- [x]  RHEL-07-020600  -  All local interactive users must have a home directory assigned in the /etc/passwd file. (#276)
- [x]  RHEL-07-020660  -  All files and directories contained in local interactive user home directories must be owned by the owner of the home directory.
- [x]  RHEL-07-020670  -  All files and directories contained in local interactive user home directories must be group-owned by a group of which the home directory owner is a member.
- [x]  RHEL-07-020690  -  All local initialization files for interactive users must be owned by the home directory user or root.
- [x]  RHEL-07-020700  -  Local initialization files for local interactive users must be group-owned by the users primary group or root.
- [x]  RHEL-07-020900  -  All system device files must be correctly labeled to prevent unauthorized modification.
- [x]  RHEL-07-021000  -  File systems that contain user home directories must be mounted to prevent files with the setuid and setgid bit set from being executed.
- [x]  RHEL-07-021020  -  File systems that are being imported via Network File System (NFS) must be mounted to prevent files with the setuid and setgid bit set from being executed.
- [x]  RHEL-07-021021  -  File systems that are being imported via Network File System (NFS) must be mounted to prevent binary files from being executed.
- [x]  RHEL-07-021030  -  All world-writable directories must be group-owned by root, sys, bin, or an application group.
- [x]  RHEL-07-030300  -  The operating system must off-load audit records onto a different system or media from the system being audited.
- [x]  RHEL-07-030310  -  The operating system must encrypt the transfer of audit records off-loaded onto a different system or media from the system being audited.
- [x]  RHEL-07-030360  -  All privileged function executions must be audited.
- [x]  RHEL-07-032010  -  The system must update the DoD-approved virus scan program every seven days or more frequently.
- [x]  RHEL-07-041003  -  The operating system must implement certificate status checking for PKI authentication.
- [x]  ~~RHEL-07-041004  -  The operating system must implement smart card logons for multifactor authentication for access to privileged accounts.~~ Item removed from STIG

**new in V2R3**

- [x] RHEL-07-010062 revent a user from overriding the screensaver lock-enabled setting for the graphical user interface. (#266)
- [ ] RHEL-07-040611 use a reverse-path filter for IPv4 network traffic when possible on all interfaces.
- [ ] RHEL-07-040612 use a reverse-path filter for IPv4 network traffic when possible by default.
- [ ] RHEL-07-020019 must have a host-based intrusion detection tool installed.

**Comment by mikerenfro** [comment]
(Can move this into a separate issue if needed)

A sizable number of the Category 2 patches are audit rules with most of the tasks repeated. Before I go to a lot of misdirected effort, would it be preferable to have individual (largely copied/pasted) tasks for each audit call or path, or something using `with_items` like:

```yaml
- hosts: localhost
  tasks:
  - debug: msg="auditctl -a always,exit -F arch={{ audit_arch }} -S {{ item.call }} -F auid>=1000 -F auid!=4294967295 -k {{ item.key }}"
    with_items:
    - { call: chown,        key: perm_mod, create: "{{ rhel_07_030370 }}" }
    - { call: lremovexattr, key: perm_mod, create: "{{ rhel_07_030490 }}" }
    - { call: creat,        key: access,   create: "{{ rhel_07_030490 }}" }
    when: item.create | default(True) | bool
```

The `with_items` version is much more compact, but wouldn't have the same verbosity of the existing tasks (like "MEDIUM | RHEL-07-010050 | PATCH | The operating system must ..."). There might also be a clever way of expanding the `with_items` loop to include task names and other attributes that I've not worked out.

**Comment by shepdelacreme** [comment]
To give a bit of background on this...Originally in the RHEL6-STIG role we had done a fair bit of AUDIT and PATCH optimization (i.e. using loops/with_items to combine similar tasks). We discussed and decided to move toward splitting AUDIT/PATCH tasks out into discrete units unless absolutely necessary. This was so that we could have good, consistent task names and it was easier to audit visually, document, etc. It also makes turning specific fixes on/off much easier.

So currently we prefer discrete tasks unless absolutely necessary. i.e. Setting the permissions and ownership on files we usually combine into a single task because it doesn't make much sense not to. We understand there is a trade off with performance because of this.

Now for the auditd rules I'm open to finding a method that allows us to continue having the ability to switch specific rules on/off with the variable system: i.e. `rhel_07_030370: true` while also simplifying and not ending up with 100+ brittle and hard to maintain `lineinfile` tasks. I think the method you outline might work if we could expand the `with_items` loop into the task names (I looked at doing this in previous versions of Ansible and it was not possible but may now be possible).

The other option may be to have an `auditd.rules` template that gets put in place with a single task. The jinja template would be parameterized based on the vars settings.

**Comment by mikerenfro** [comment]
Let me get a proper feature branch going for this, but I think I've got a better proof of concept that includes task names (never used Ansible before 2.4, so not familiar with older limitations).

I'm not stuck on using a loop, regardless. Just want to get the patch coverage done as much as possible for our own audits.

**Comment by shepdelacreme** [comment]
Thanks! Also do you intend to use `auditctl` statements like the above for each patch task for the audit rules? Or will you be writing them to `/etc/audit/audit.rules` somehow?

**Comment by mikerenfro** [comment]
Please check out [this set of changes](https://github.com/MindPointGroup/RHEL7-STIG/compare/devel...mikerenfro:feature-auditd-loop), which should be complete for system calls, but not for privileged commands and log files. Will also need to figure out cherry-picking the right commits for a real pull request, since I needed to temporarily disable most of the patches in my test environment.

**Comment by shepdelacreme** [comment]
Ok I see. I think we need to be able to remove lines as well so that rules can be switched on/off. So maybe if we use the value of create to specify `state=present` or `state=absent`? 

Thoughts?

**Comment by shepdelacreme** [comment]
i.e. change the with_items lines to:
```yaml
- {id: "030370", call: "chown", key: "perm_mod", state: "{{ (rhel_07_030370) | ternary('present','absent') }}"}
```

And the task to:
```yaml
- name: "MEDIUM | RHEL-07-{{ item.id }} | PATCH | All uses of the {{ item.call }} command must be audited."
  lineinfile:
    path: "/etc/audit/rules.d/rhel7stig_system_calls.rules"
    create: yes
    owner: root
    group: root
    mode: 0600
    line: "-a always,exit -F arch=b64 -S {{ item.call }} -F auid>=1000 -F auid!=4294967295 -k {{ item.key }}"
    state: "{{ item.state }}"
```

I haven't tested but I think that ternary should work.

**Comment by mikerenfro** [comment]
Looks reasonable. May have to put it off until tomorrow, though.

**Comment by mikerenfro** [comment]
Things got a bit more complicated. Between the audit entries for syscall exits and file watches:

- some syscall exits filter on the call itself, others filter on a specific path.
- some filter on AUIDs for regular users, others don't.
- some filter on specific permissions, others don't.

I think this is fixable by defining dicts with attributes of `call`, `path`, `include_all_auids`. `exclude_unknown_auid` ,`extrafields`, and `key`. It'll take a bit longer to refactor, though.

**Comment by dfederlein** [comment]
Checked off a few that are part of a PR from the dfed branch

**Comment by jamescassell** [comment]
> Checked off a few that are part of a PR from the dfed branch

I don't see 010500 (multi-factor) in that PR #245 (I assume that's what you are referring to.)  Still notimplemented here: https://github.com/MindPointGroup/RHEL7-STIG/blob/3fb4e6a4e5a5b257844f778d57313b048703e850/tasks/fix-cat2.yml#L592-L598

I just cleared the check mark from 010500.  Let me know if this is in error.

**Comment by dfederlein** [comment]
You are correct, I have not committed those changes yet.

**Comment by georgenalen** [comment]
Hello,
I wanted to reach out and let you know that this issue is being closed. We have re-worked the role and want to start with a fresh issues list with this latest version. There was a post in the Ansible-Lockdown google group (https://groups.google.com/g/ansible-lockdown) with the details of the changes that are coming. Please checkout the thread titled RHEL 7 CIS and STIG Changes for all of the details, I also have the message pasted at below.
Please as you use the latest version and open issue tickets as you find them, it is the best way for us to improve the role for everyone. Thank you for being part of the community and providing awareness of problems or advice on improvement. Reporting is a huge part of improving this project.

--------------------------------
Hello,
Thank you to everyone in the Ansible-Lockdown community who has contributed to RHEL7 STIG/CIS. Our team at MindPoint Group has been working with the entirety of the Ansible-Lockdown project, and we have some significant updates for both RHEL 7 STIG and CIS. With these updates, some larger changes have been made. I have these changes/updates outlined below.
Testing:
1.	CI/CD - We have implemented some automated testing pipelines to test pull requests into the devel and main branches. With the current workflow, the community will PR into the devel branch (never the main branch) for review by the administrators. When your PR is created, the first check will remain the DCO check. The second check is a functional testing pipeline that will automatically perform a functional test of the branch the PR is initiated from. Once both tests pass, someone from the Administrator Team will review the changes and merge them into the devel branch. From there, an additional review is completed before the devel branch is merged into the main branch. Only the Admin Team will perform PRs/merges into the main branch. There is also an automated pipeline for PRs from devel to main. Please do not edit the .github/workflows files since those are used as part of the pipeline.
2.	Compliance Checking – MindPoint Group has been working to create our own compliance audit scan tool. The tool uses a goss framework executable to run custom checks that we have created. The goal is to provide a more thorough check for control compliance and decrease the number of false positives/negatives. For example, it will check the configuration file related to the control and as well as checking if that configuration is active. With a smarter scan, we can hopefully identify attempts to trick scanners as well (for example stacking a parameter in a config file where the first instance is enabled and second disabled. Most audit tools search for the first instance but the application might look for the last instance of the parameter, thus making the scanning tool think it's enabled). In testing, we have found that our audit scan runs significantly faster than other audit tools, reducing audit times. Our audit tool and profiles will have their own repositories in the Ansible-Lockdown org, but within the remediation role there will be an integrated way to incorporate the audit. Keep an eye out for the audit tools as they are released. We plan on developing a goss audit profile for each current remediation role. Going forward, we plan to release a remediation role and goss audit tool profile simultaneously.
Role Updates:
1.	RHEL 7 STIG/CIS – We have re-written much of the RHEL 7 STIG and CIS roles to increase clarity and readability and address some functionality items. We performed these updates while creating our goss testing framework for each of these roles. We plan on pushing our update to the devel and main branches. We will move the current devel and master branches to a devel_stable_ and master_stable_ branch in the respective repositories. Accordingly, community members who rely on the current version can still use that version going forward; this process will not remove what is currently there. The latest versions of the roles have also been updated to comply with the latest benchmarks.
2.	Role Architecture – All roles will change with regard to the structure in the tasks folder. Taking CIS as an example, there will be a folder per section and yaml files for each sub-section. For example control 1.2.1 in CIS will be located in RHEL7-CIS/tasks/section_1/cis_1.2.x.yml. The cis_1.2.x.yml file will contain all controls related to section 1.2.x. This will hopefully make updates to roles a bit easier with less risk. This matches the architecture of our audit tool, creating consistency across remediation and audit platforms. The end goal is to repeat this architecture (the best we can) on STIG roles, but we are starting with CIS.
3.	Existing PRs and Issues – With all of these changes comes the task of cleaning up existing PR’s and issues. Our plan is to close all of the existing PR’s and issues because of the re-work. Our team is growing and should be able to stay on top of the new issues and PRs as they come in.
Again, I would like to thank the community for your involvement in this project. The input and work from the community has contributed significantly to the success of this project. Please keep an eye out for these changes, which will be rolling out in the coming weeks.
